### PR TITLE
Parallax V2

### PR DESCRIPTION
**Pull request by Helldwin**
Parallax plus effectif

### CODE REVIEW

**Comment by matiboux** [comment]
I'm gonna do some refactoring ✨

**Comment by matiboux** [comment]
New features:
- Added `onResize` event listener to increase canvas size and reset stars if window got larger.
- Centered the canvas element in its fullscreen parent (in case the canvas is larger than the screen).
- Compute the number of stars ("quantity") based on density.

Density is defined as the "number of stars per pixel".
As such, it is a float number between 0 and 1, inclusive.

I should add this note in the source code and a condition to verify the density value.

**Comment by matiboux** [comment]
New features:
- Added new `Parallax` component for refactoring
- Starfield stars animation is started unless user prefers reduced motion.

User preference on motion is check using media query: `(prefers-reduced-motion: reduce)`.

**Comment by matiboux** [comment]
@Helldwin I think I'm done, can you check?

**Review by Helldwin — COMMENTED** [review]
I think it's good to be merged

**Review by matiboux — APPROVED** [review]

**Pull request merged**
